# Site settings
title: Frederick Douglass in Britain
header-img: img/london-lo.jpg
email: hannahrose.murray78@gmail.com
copyright_name: Hannah Murray
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://frederickdouglassinbritain.com"
twitter_username: Hannah_RoseM
email_username: hannahrose.murray78@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

#MJG dont really need these (once removed from all templates)
gems: [jekyll-paginate, jekyll-feed]
